### ISSUE TITLE
【一般】版本库开通界面，选择默认路径，点击确定按钮，无法开通版本库。

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-MGMT-DEV#2]
环境win7
浏览器：火狐
测试环境：
管理门户：http://10.1.245.248:16002/paas-console
[概要]：【一般】版本库开通界面，选择默认路径，点击确定按钮，无法开通版本库。
[详细步骤]：
[管理门户]租户管理->版本库开通，选择一条数据后，点击开通版本库，在弹出的浮层，选择默认路径，点击确定时，不能开通成功，必须修改默认路径后，才可正常开通版本库。
[实际结果]：
选择默认路径，无法开通版本库
[预期结果]:
默认路径，可以开通版本库。

**Comment by guohong1** [comment]
已修改

**Comment by xiexm** [comment]
验证通过。
